const CSS = String.raw`
:root{--ink:#05080e;--paper:#f3ead7;--muted:#b9af9d;--line:rgba(243,234,215,.16);--mint:#14f195;--gold:#ffd76e}html,body{margin:0;min-height:100%;background:var(--ink);color:var(--paper)}.mh{min-height:100vh;padding:18px;background:radial-gradient(circle at 14% 0%,rgba(20,241,149,.11),transparent 30rem),linear-gradient(180deg,#07101a,#03060b);font-family:Outfit,Geist,system-ui,sans-serif}.hero,.card{border:1px solid var(--line);border-radius:22px;background:linear-gradient(180deg,rgba(12,22,34,.96),rgba(5,10,18,.96));box-shadow:0 22px 60px rgba(0,0,0,.34)}.hero{padding:20px;margin-bottom:14px}.k{color:var(--gold);font:900 11px/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1{font-family:Georgia,serif;font-size:clamp(38px,6vw,72px);line-height:.9;margin:8px 0}p{color:#d8cfb7;line-height:1.45}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.card{display:grid;gap:8px;padding:16px;color:inherit;text-decoration:none}.card:hover{border-color:rgba(20,241,149,.45);transform:translateY(-1px)}.badge{display:inline-flex;width:max-content;padding:4px 8px;border-radius:999px;background:rgba(20,241,149,.12);border:1px solid rgba(20,241,149,.25);color:#bcf7d6;font:900 11px/1 ui-monospace,monospace}.todo{opacity:.62}.row{display:flex;gap:8px;flex-wrap:wrap}.btn{border:1px solid var(--line);border-radius:999px;background:#111c2b;color:var(--paper);padding:8px 12px;text-decoration:none;font-weight:900}`;
const cards = [
  ["Bomb Fuse Debug", "/admin/mechanics/bombs", "Inspect active destroy tools, repair legacy missing fuses, and force-resolve expired bombs."],
  ["Science + Crafting", "/admin/mechanics/science-crafting", "Test Academy science, science-only craft costs, destroy-tool crafting, and pack counts."],
  ["Keep Vault + Coins", "/admin/keep-coin-test", "Spawn/siege a neutral Keep, verify visible stored coins, owned-slot coin payout, next Keep spawn, and bombs."],
  ["Player Resources", "/admin/player-resources", "Grant/set resources for a specific player: coins, science, materials, energy, HP, XP, and bombs."],
  ["Refactor Map", "/admin/mechanics/refactor", "Track which backend/frontend pieces have been split from monoliths and what should be extracted next."],
  ["World Wonders Studio", "/admin/wonders", "Generate one real-AI mesh recipe in isolation before exposing it to World Wonder placement."],
  ["Audio Studio", "/admin/audio", "Upload and preview runtime background music."],
  ["Atlas Debug", "/admin/debug/atlas", "Check published runtime atlas versions, bounds, pads, and coin cells."],
  ["Economy Studio", "/admin/economy", "Tune Academy, science, Workshop, bombs, Keeps, and World Wonders."],
  ["Future: Roads", "#", "Test path wear / road growth from repeated player movement."],
  ["Future: Events", "#", "Test timed map events near active players only."],
];
export default function MechanicsHubPage(){return <><style dangerouslySetInnerHTML={{__html:CSS}}/><main className="mh"><section className="hero"><div className="row"><a className="btn" href="/admin">← Admin</a><a className="btn" href="/">Open game</a></div><p className="k">SolCraft modular test benches</p><h1>Mechanics Labs</h1><p>Each mechanic should get a small test page before it becomes part of the main game UI. This is how we safely break the frontend/backend monoliths apart.</p></section><section className="grid">{cards.map(([title,href,body])=><a className={href==="#"?"card todo":"card"} href={href}><span className="badge">{href==="#"?"planned":"open"}</span><h2>{title}</h2><p>{body}</p></a>)}</section></main></>}
