// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
import { DESTROY_TOOLS, RECIPES, COSTI } from "@server/shared";
import { fetchGameState, gameAction, readSavedGameAuth, stateMe } from "../../../../client/admin/gameSession";

const rootId = "solcraft-science-crafting-lab";
let mounted = false;
let auth:any = null;
let snap:any = null;
let err = "";
let msg = "";
let busy = false;
const SCIENCE_RECIPES = RECIPES.slice(0, 12);

const CSS = String.raw`
:root{--ink:#05080e;--paper:#f3ead7;--muted:#b9af9d;--line:rgba(243,234,215,.16);--mint:#14f195;--gold:#ffd76e;--bad:#ff8d78}html,body{margin:0;min-height:100%;background:var(--ink);color:var(--paper)}.scl{min-height:100vh;padding:18px;background:radial-gradient(circle at 14% 0%,rgba(20,241,149,.11),transparent 30rem),linear-gradient(180deg,#07101a,#03060b);font-family:Outfit,Geist,system-ui,sans-serif}.hero,.panel,.card{border:1px solid var(--line);border-radius:22px;background:linear-gradient(180deg,rgba(12,22,34,.96),rgba(5,10,18,.96));box-shadow:0 22px 60px rgba(0,0,0,.34)}.hero,.panel{padding:18px;margin-bottom:12px}.k{color:var(--gold);font:900 11px/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1{font-family:Georgia,serif;font-size:clamp(36px,6vw,68px);line-height:.9;margin:8px 0}h2,h3{margin:.2em 0}p{color:#d8cfb7;line-height:1.45}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.btn{border:1px solid var(--line);border-radius:999px;background:#111c2b;color:var(--paper);padding:8px 12px;text-decoration:none;font-weight:900;cursor:pointer}.btn.primary{background:var(--mint);border-color:var(--mint);color:#06120d}.btn.warn{background:rgba(255,215,110,.14);border-color:rgba(255,215,110,.32);color:#ffe6aa}.btn:disabled{opacity:.48;cursor:not-allowed}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:10px}.card{padding:13px;display:grid;gap:8px}.metric b{font-size:28px;color:var(--mint)}.tiny{color:var(--muted);font:800 12px/1.4 ui-monospace,monospace}.ok{color:#baffdf}.bad{color:#ffb7aa}.pill{display:inline-flex;width:max-content;border-radius:999px;padding:4px 8px;background:rgba(20,241,149,.11);border:1px solid rgba(20,241,149,.24);color:#baffdf;font:900 10px/1 ui-monospace,monospace}.mono{white-space:pre-wrap;font:800 12px/1.45 ui-monospace,monospace;color:#fff0c8;background:rgba(0,0,0,.22);border-radius:14px;padding:12px;overflow:auto}`;

function cost(cost:any){return Object.entries(cost||{}).filter(([,v])=>Number(v)>0).map(([k,v])=>`${Math.ceil(Number(v))}${COSTI[k]||k}`).join(" ") || "free";}
function packBombs(me:any){const counts:any={}; for(const it of me?.pack||[]) if(it?.t==="bomb") counts[it.id]=(counts[it.id]||0)+1; return counts;}
async function load(){busy=true;err="";msg="";paint();try{auth=readSavedGameAuth();snap=await fetchGameState(auth,{rev:0,mapRev:-1});}catch(e:any){err=String(e?.message||e)}busy=false;paint();}
async function act(type:string,payload:any={}){busy=true;err="";msg="";paint();try{const r=await gameAction(auth||readSavedGameAuth(),type,payload);msg=r?.note||"Action succeeded.";await load();}catch(e:any){err=String(e?.message||e);busy=false;paint();}}
function MeCard(){const me=stateMe(snap)||{};const inv=me.inv||{};const bombs=packBombs(me);return <section className="panel"><h2>Current player</h2><div className="grid"><div className="card metric"><span className="tiny">player</span><b>{me.name||"—"}</b><span className="tiny">pid {me.id||auth?.pid||"?"}</span></div><div className="card metric"><span className="tiny">science</span><b>{Math.floor(inv.sc||0)} / {Math.floor(me.scienceCap||me.storageCap?.sc||0)}</b><span className="tiny">Academies raise this cap.</span></div><div className="card metric"><span className="tiny">pack</span><b>{(me.pack||[]).filter(Boolean).length}</b><span className="tiny">bombs {JSON.stringify(bombs)}</span></div></div></section>}
function Bombs(){return <section className="panel"><h2>Science-only destroy tools</h2><p>Crafting must spend science only. No Workshop, stone, planks, food, or other hidden gate.</p><div className="grid">{DESTROY_TOOLS.map((b:any)=><div className="card"><span className="pill">{b.glyph} {b.id}</span><h3>{b.name}</h3><p>{b.blurb}</p><p className="tiny">cost {cost(b.cost)} · fuse {Math.round((b.fuseMs||0)/1000)}s · radius {b.radius}</p><button className="btn primary" disabled={busy} data-action="makeBomb" data-id={b.id}>Craft {b.name}</button></div>)}</div></section>}
function Recipes(){return <section className="panel"><h2>Science-only supplies / gear</h2><p>These recipes should also be science-only and should not require Forge, Workshop, or Alchemy.</p><div className="grid">{SCIENCE_RECIPES.map((r:any)=><div className="card"><span className="pill">{r.glyph} {r.id}</span><h3>{r.name}</h3><p>{r.blurb}</p><p className="tiny">cost {cost(r.cost)}</p><button className="btn" disabled={busy} data-action="craft" data-id={r.id}>Craft</button></div>)}</div></section>}
function App(){return <main className="scl"><style>{CSS}</style><section className="hero"><div className="row"><a className="btn" href="/admin/mechanics">← Mechanics</a><a className="btn" href="/admin/player-resources">Give science</a><a className="btn" href="/">Open game</a><button className="btn primary" data-action="reload">Reload state</button></div><p className="k">SolCraft mechanic lab</p><h1>Science + Crafting</h1><p>Test the Academy → science → craft tools loop without using the big game HUD. This page calls the same `/api/action` dispatcher as the real game.</p>{busy?<p className="tiny">Working…</p>:null}{msg?<p className="ok">{msg}</p>:null}{err?<p className="bad">{err}</p>:null}</section><MeCard/><Bombs/><Recipes/><section className="panel"><h2>Contract</h2><pre className="mono">{`Buildings = wood only\nAcademy = passive science and science cap\nCrafting/deployables = science only\nKeeps = breached by crafted tools\nKeeps pay coins\nWorld Wonders spend coins`}</pre></section></main>}
function paint(){const root=document.getElementById(rootId); if(root)render(<App/>,root)}
export default function mount(){const root=document.getElementById(rootId);if(!root||mounted)return;mounted=true;root.addEventListener("click",(ev)=>{const el=(ev.target as HTMLElement).closest("[data-action]") as HTMLElement|null;if(!el||!root.contains(el))return;ev.preventDefault();const a=el.dataset.action;if(a==="reload")load();else if(a==="makeBomb")act("makeBomb",{variant:el.dataset.id});else if(a==="craft")act("craft",{id:el.dataset.id});});paint();load();}
