const ADMIN_HOME_CSS = String.raw`
:root{--ink:#05080e;--panel:#0b1420;--paper:#f3ead7;--muted:#b9af9d;--line:rgba(243,234,215,.16);--mint:#14f195;--gold:#c79337;--danger:#ff705c}html,body{margin:0;min-height:100%;background:#05080e;color:var(--paper);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif}.admin-home{min-height:100vh;padding:18px;background:radial-gradient(circle at 14% 0%,rgba(20,241,149,.12),transparent 30rem),linear-gradient(180deg,#07101a,#03060b)}.hero,.card{border:1px solid var(--line);border-radius:22px;background:linear-gradient(180deg,rgba(12,22,34,.96),rgba(5,10,18,.96));box-shadow:0 22px 60px rgba(0,0,0,.35)}.hero{padding:22px;margin-bottom:14px}.kicker{margin:0 0 8px;color:var(--gold);font:900 11px/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1,h2,h3{margin:0;font-family:Georgia,serif;letter-spacing:-.04em}h1{font-size:clamp(38px,6vw,72px);line-height:.9}.hero p,.card p{color:#d8cfb7;line-height:1.45}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.card{display:grid;gap:10px;padding:16px;text-decoration:none;color:inherit}.card:hover{border-color:rgba(20,241,149,.45);transform:translateY(-1px)}.card b{font-size:20px}.badge{display:inline-flex;width:max-content;padding:4px 8px;border-radius:999px;background:rgba(20,241,149,.12);border:1px solid rgba(20,241,149,.25);color:#bcf7d6;font:900 11px/1 ui-monospace,monospace}.danger{background:rgba(255,112,92,.12);border-color:rgba(255,112,92,.25);color:#ffd4cc}.todo{margin-top:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.todo ul{margin:8px 0 0;padding-left:18px;color:#d8cfb7;line-height:1.6}@media(max-width:900px){.grid,.todo{grid-template-columns:1fr}.admin-home{padding:12px}}`;
const cards = [
  ["Atlas Studio", "/admin/atlas", "Production atlas upload, crop, pixel alignment, publish/runtime validation."],
  ["Doll Studio", "/admin/doll", "Character doll preview and atlas handoff."],
  ["Terrain Lab", "/admin/terrain", "Procedural terrain warmth/texture controls."],
  ["Mechanics Labs", "/admin/mechanics", "Focused test pages for Keeps, AI buildings, resources, map events, and future systems."],
  ["World Sync + Player View", "/admin/world-sync", "Pull production world into local SQLite and open the game as any player for city/Wonder inspection."],
  ["Player Resources", "/admin/player-resources", "Grant/set resources for a specific player: coins, science, materials, energy, HP, XP, and bombs."],
  ["Keep Coin Test", "/admin/keep-coin-test", "Spawn/siege Keeps and validate coin-vault payout loops."],
  ["World Wonders Studio", "/admin/wonders", "Real AI mesh-generation lab for player World Wonders."],
  ["Wonder Template Lab", "/admin/wonder-templates", "Hand-authored quality examples for school, skyscraper, market, temple, and other prompt archetypes."],
  ["Audio Studio", "/admin/audio", "Upload background music and tune runtime sound settings."],
  ["Client Refresh", "/admin/refresh", "Force active players to refresh after a deploy or rendering/gameplay patch."],
  ["Economy Studio", "/admin/economy", "Tune energy, coins, science, caps, costs, and building economy roles."],
  ["Bank Studio", "/admin/bank", "Solwal/Sowl token mint, deposit wallets, withdrawal queue, scans, config, and errors."],
  ["Debug · TradJS", "/admin/debug/tradjs", "Repro tests for tabs, filtered lists, and claim-style buttons."],
  ["Debug · Atlas", "/admin/debug/atlas", "Runtime atlas status, versions, bounds, pads, modes."],
  ["Debug · Economy", "/admin/debug/economy", "World counts, circulation, login token gate, controls, active players."],
  ["Debug · Player State", "/admin/debug/player-state", "Read-only player resource/tile/storage snapshot."],
];
export default function AdminHomePage(){return <><style dangerouslySetInnerHTML={{__html:ADMIN_HOME_CSS}}/><main className="admin-home"><section className="hero"><p className="kicker">SolCraft operator dashboard</p><h1>Admin Control Room</h1><p>Use this page as the safe entry point for atlas work, mechanics testing, resource grants, runtime debugging, and economy/player inspection.</p></section><section className="grid">{cards.map(([title,href,body])=><a className="card" href={href}><span className="badge">Open</span><b>{title}</b><p>{body}</p></a>)}</section><section className="todo"><div className="card"><span className="badge">Checklist</span><h2>Before remote sync</h2><ul><li>Open Atlas Debug and verify runtime version/bounds.</li><li>Open Player Resources only for deliberate test grants.</li><li>Open Economy Debug and check players/resources/tiles.</li><li>Force refresh on remote only after migration is live.</li></ul></div><div className="card"><span className="badge danger">Reliability rules</span><h2>Non-negotiables</h2><ul><li>Server rejects bad actions with reasons.</li><li>No silent tile/resource deletion.</li><li>Admin resource grants are explicit and auditable by action.</li><li>Debug pages reproduce panel bugs before patches ship.</li></ul></div></section></main></>}
