// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
const rootId="player-debug-root";let mounted=false;let data:any=null;let err="";let busy=false;
const CSS=`.dbg{min-height:100vh;padding:16px;background:#05080e;color:#f3ead7;font-family:Inter,system-ui,sans-serif}.panel{border:1px solid rgba(243,234,215,.16);border-radius:18px;background:#0b1420;padding:14px;margin:12px 0}.btn{border:1px solid rgba(243,234,215,.18);border-radius:999px;background:#111c2b;color:#f3ead7;padding:8px 12px;font-weight:900;cursor:pointer}.table{display:grid;gap:8px}.row{display:grid;grid-template-columns:54px minmax(120px,1fr) repeat(8,minmax(54px,.5fr));gap:6px;align-items:center;border:1px solid rgba(243,234,215,.1);border-radius:12px;padding:8px;background:rgba(243,234,215,.04)}.head{color:#c79337;font:900 11px/1 ui-monospace,monospace;text-transform:uppercase}.bad{color:#ff705c}@media(max-width:900px){.row{grid-template-columns:42px minmax(120px,1fr) repeat(3,minmax(54px,.5fr))}.row span:nth-child(n+6){display:none}}`;
async function load(){busy=true;err="";paint();try{const r=await fetch("/api/admin/debug/summary",{cache:"no-store"});data=await r.json();if(!r.ok||data?.ok===false)throw new Error(data?.msg||r.statusText)}catch(e:any){err=String(e?.message||e)}busy=false;paint()}
function users(){return data?.economy?.users||data?.users||[]}
function App(){return <main className="dbg"><style>{CSS}</style><a className="btn" href="/admin">← Admin</a> <button className="btn" data-action="reload">Reload</button><h1>Player state debug</h1><p>Read-only snapshot for territory/resource/storage regressions.</p>{busy?<p>Loading…</p>:null}{err?<p className="bad">{err}</p>:null}<section className="panel table"><div className="row head"><span>ID</span><span>Name</span><span>Tiles</span><span>Build</span><span>Energy</span><span>HP</span><span>Wood</span><span>Stone</span><span>Gold</span><span>Safe</span></div>{users().map((u:any)=><div className="row"><span>{u.id}</span><b>{u.name}</b><span>{u.tiles}</span><span>{u.buildings}</span><span>{u.energy}/{u.maxEnergy}</span><span>{u.hp}</span><span>{u.wood}</span><span>{u.stone}</span><span>{u.gold}</span><span>{u.strongbox??u.vault}</span></div>)}</section></main>}
function paint(){render(<App/>,document.getElementById(rootId)!)}
export default function mount(){const root=document.getElementById(rootId);if(!root||mounted)return;mounted=true;root.addEventListener("click",ev=>{const el=(ev.target as HTMLElement).closest("[data-action]") as HTMLElement|null;if(el?.dataset.action==="reload")load()});load()}
