// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
const rootId="economy-debug-root";let mounted=false;let data:any=null;let err="";let busy=false;let saving=false;
const CSS=`.dbg{min-height:100vh;padding:16px;background:#05080e;color:#f3ead7;font-family:Inter,system-ui,sans-serif}.panel{border:1px solid rgba(243,234,215,.16);border-radius:18px;background:#0b1420;padding:14px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{border:1px solid rgba(243,234,215,.14);border-radius:14px;background:rgba(243,234,215,.05);padding:10px}.btn{border:1px solid rgba(243,234,215,.18);border-radius:999px;background:#111c2b;color:#f3ead7;padding:8px 12px;font-weight:900;cursor:pointer}.btn.primary{background:#14f195;color:#06130d;border-color:#14f195}.mono{font:12px/1.35 ui-monospace,monospace;white-space:pre-wrap;max-height:320px;overflow:auto}.bad{color:#ff705c}.ok{color:#14f195}label{display:grid;gap:5px;font-weight:900;color:#d8cfb7}input,textarea{border:1px solid rgba(243,234,215,.18);border-radius:12px;background:#07101a;color:#f3ead7;padding:9px;font:inherit}input[type=checkbox]{width:20px;height:20px}.hint{font-size:12px;color:#a9b9c3;margin:4px 0 0}@media(max-width:850px){.grid,.form{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.grid,.form{grid-template-columns:1fr}}`;
async function load(){busy=true;err="";paint();try{const r=await fetch("/api/admin/debug/summary",{cache:"no-store"});data=await r.json();if(!r.ok||data?.ok===false)throw new Error(data?.msg||r.statusText)}catch(e:any){err=String(e?.message||e)}busy=false;paint()}

async function saveBank(){const root=document.getElementById(rootId)!;const val=(id:string)=>(root.querySelector(`#${id}`) as HTMLInputElement|HTMLTextAreaElement)?.value||"";const checked=(id:string)=>!!(root.querySelector(`#${id}`) as HTMLInputElement)?.checked;saving=true;err="";paint();try{const body={action:"save-bank",bank:{enabled:checked("bk-enabled"),token:val("bk-token"),tokenLabel:val("bk-label"),bankWallet:val("bk-bank-wallet"),treasuryWallet:val("bk-treasury"),rpcEndpoint:val("bk-rpc"),dryRunOnly:checked("bk-dry"),minWithdrawUi:val("bk-min"),decimals:Number(val("bk-decimals")||0)}};const r=await fetch("/api/admin/debug/summary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(j?.msg||r.statusText);await load()}catch(e:any){err=String(e?.message||e)}saving=false;paint()}
async function saveLoginGate(){const root=document.getElementById(rootId)!;const val=(id:string)=>(root.querySelector(`#${id}`) as HTMLInputElement|HTMLTextAreaElement)?.value||"";const checked=(id:string)=>!!(root.querySelector(`#${id}`) as HTMLInputElement)?.checked;saving=true;err="";paint();try{const body={action:"save-login-gate",loginGate:{enabled:checked("lg-enabled"),tokenMint:val("lg-mint"),tokenLabel:val("lg-label"),minUi:val("lg-min"),decimals:Number(val("lg-decimals")||0),rpcEndpoint:val("lg-rpc"),message:val("lg-msg")}};const r=await fetch("/api/admin/debug/summary",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(j?.msg||r.statusText);await load()}catch(e:any){err=String(e?.message||e)}saving=false;paint()}
function stat(k:string,v:any){return <div className="card"><p>{k}</p><h2>{String(v??0)}</h2></div>}
function LoginGatePanel(){const g=data?.loginGate||data?.economy?.loginGate||{};return <section className="panel"><h2>Login token gate</h2><p className="hint">Production play can require Phantom plus a minimum SPL token balance. Spectate stays read-only. Configure locally, then sync remote with migration/deploy.</p><div className="form"><label><span>Enabled</span><input id="lg-enabled" type="checkbox" checked={!!g.enabled}/></label><label><span>Token label</span><input id="lg-label" value={g.tokenLabel||"$CRAFTS"}/></label><label><span>Required token mint address</span><input id="lg-mint" value={g.tokenMint||""} placeholder="SPL token mint public key"/></label><label><span>Minimum balance</span><input id="lg-min" value={g.minUi||"1"}/></label><label><span>Token decimals</span><input id="lg-decimals" type="number" min="0" max="12" value={g.decimals??6}/></label><label><span>RPC endpoint</span><input id="lg-rpc" value={g.rpcEndpoint||""} placeholder="https://..."/></label><label style="grid-column:1/-1"><span>Login message</span><textarea id="lg-msg" rows="2">{g.message||"Hold the required SolCrafts token in your Phantom wallet to play."}</textarea></label></div><p className={g.enabled&&g.configured?"ok":"hint"}>{g.enabled ? (g.configured ? "Token gate configured." : "Enabled but missing token mint or RPC endpoint.") : "Token gate disabled."}</p><button className="btn primary" data-action="save-login-gate" disabled={saving}>{saving?"Saving…":"Save login token gate"}</button></section>}

function BankConfigPanel(){const b=data?.bank||data?.economy?.bank||{};const cfg=b.config||b||{};const summary=b.summary||{};return <section className="panel"><h2>Solwal / Sowl bank</h2><p className="hint">Bank configuration moved to Bank Studio so debug economy stays read-only.</p><div className="grid">{stat("enabled",cfg.enabled?"yes":"no")}{stat("dry run",cfg.dryRunOnly!==false?"yes":"no")}{stat("deposit wallets",summary.depositWallets||0)}{stat("pending",summary.pendingWithdrawals||0)}</div><p><a className="btn primary" href="/admin/bank">Open Bank Studio</a></p></section>}
function App(){const e=data?.economy||data||{};const c=e.counts||{};const circ=e.circulation||{};return <main className="dbg"><style>{CSS}</style><a className="btn" href="/admin">← Admin</a> <button className="btn" data-action="reload">Reload</button><h1>Economy debug</h1>{busy?<p>Loading…</p>:null}{err?<p className="bad">{err}</p>:null}<LoginGatePanel/><BankConfigPanel/><section className="panel"><h2>World counts</h2><div className="grid">{stat("players",c.players)}{stat("active",c.activePlayers)}{stat("tiles",c.tiles)}{stat("buildings",c.buildings)}{stat("destroy tools",c.activeDestroyTools)}{stat("loot",c.loot)}{stat("offers",c.offers)}{stat("mints",c.activeGoldMines)}</div></section><section className="panel"><h2>Circulation</h2><div className="grid">{Object.entries(circ).map(([k,v])=>stat(k,v))}</div></section><section className="panel"><h2>Controls / rules</h2><pre className="mono">{JSON.stringify({requiredVersion:data?.requiredVersion,loginGate:data?.loginGate,controls:e.controls,rules:e.rules},null,2)}</pre></section><section className="panel"><h2>Recent admin/economy events</h2><pre className="mono">{JSON.stringify((e.eventLog||[]).slice(-50),null,2)}</pre></section></main>}
function paint(){render(<App/>,document.getElementById(rootId)!)}
export default function mount(){const root=document.getElementById(rootId);if(!root||mounted)return;mounted=true;root.addEventListener("click",ev=>{const el=(ev.target as HTMLElement).closest("[data-action]") as HTMLElement|null;if(el?.dataset.action==="reload")load();if(el?.dataset.action==="save-login-gate")saveLoginGate();if(el?.dataset.action==="save-bank")saveBank()});load()}
