// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
const rootId="atlas-debug-root";let mounted=false;let data:any=null;let err="";let busy=false;
const CSS=`.dbg{min-height:100vh;padding:16px;background:#05080e;color:#f3ead7;font-family:Inter,system-ui,sans-serif}.dbg *{box-sizing:border-box}.panel{border:1px solid rgba(243,234,215,.16);border-radius:18px;background:#0b1420;padding:14px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:12px}.card{border:1px solid rgba(243,234,215,.14);border-radius:14px;background:rgba(243,234,215,.05);padding:10px;min-width:0}.card img{width:100%;height:90px;object-fit:contain;background:repeating-conic-gradient(rgba(255,255,255,.06) 0 25%,rgba(0,0,0,.1) 0 50%) 50%/12px 12px;border-radius:10px}.btn{border:1px solid rgba(243,234,215,.18);border-radius:999px;background:#111c2b;color:#f3ead7;padding:8px 12px;font-weight:900;cursor:pointer}.ok{color:#14f195}.warn{color:#ffd76e}.bad{color:#ff705c}.mono{font:12px/1.35 ui-monospace,monospace;white-space:pre-wrap;overflow:auto}@media(max-width:1100px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.grid{grid-template-columns:1fr}}`;
async function load(){busy=true;err="";paint();try{const r=await fetch("/api/admin/atlas?debug=1",{cache:"no-store"});data=await r.json();if(!r.ok||data?.ok===false)throw new Error(data?.msg||r.statusText)}catch(e:any){err=String(e?.message||e)}busy=false;paint()}
function versions(){return data?.versions||data?.images||data?.saved||[]}
function App(){const pubs=data?.publishedByAtlas||data?.published||{};const bounds=data?.boundsByAtlas||data?.bounds||{};const pads=data?.padByAtlas||data?.pads||{};return <main className="dbg"><style>{CSS}</style><a className="btn" href="/admin">← Admin</a> <a className="btn" href="/admin/atlas">Open Atlas Studio</a> <button className="btn" data-action="reload">Reload</button><h1>Atlas runtime debug</h1>{busy?<p>Loading…</p>:null}{err?<p className="bad">{err}</p>:null}<section className="panel"><h2>Runtime status</h2><div className="grid">{["terrain","building","fx","ui","doll"].map(id=>{const p=pubs[id];return <div className="card"><b>{id}</b><p className={p?"ok":"bad"}>{p?"published":"not published"}</p>{p?.url?<img src={p.url}/>:null}<p className="mono">bounds {JSON.stringify(bounds[id]||null)}\npad {String(pads[id]??0)}\n{p?.id||""}</p><a className="btn" href={`/admin/atlas?atlas=${id}`}>Edit</a></div>})}</div></section><section className="panel"><h2>Saved versions ({versions().length})</h2><div className="grid">{versions().slice(0,60).map((v:any)=><div className="card"><b>{v.label||v.id}</b><p>{v.atlasId} · {v.w||"?"}×{v.h||"?"}</p>{v.url?<img src={v.url}/>:null}<p className="mono">{v.id}</p></div>)}</div></section></main>}
function paint(){render(<App/>,document.getElementById(rootId)!)}
export default function mount(){const root=document.getElementById(rootId);if(!root||mounted)return;mounted=true;root.addEventListener("click",ev=>{const el=(ev.target as HTMLElement).closest("[data-action]") as HTMLElement|null;if(el?.dataset.action==="reload")load()});load()}
