// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
import { createMeasure } from "measure-fn";
import { readAdminKey, writeAdminKey, adminKeyHeaders, explainAdminError } from "../../../client/admin/adminKey";

const m = createMeasure("admin.bank", { maxResultLength: 220 });
const rootId = "solcraft-admin-bank";
let mounted = false;
let data:any = null;
let err = "";
let msg = "";
let busy = false;
let adminKey = "";

const CSS = String.raw`
.admin-bank{min-height:100dvh;overflow:auto;padding:16px;background:radial-gradient(circle at 12% 0%,rgba(20,241,149,.12),transparent 30rem),linear-gradient(180deg,#07101a,#03060b);color:#f3ead7;font-family:Inter,system-ui,sans-serif}.hero,.panel,.card{border:1px solid rgba(243,234,215,.16);border-radius:20px;background:linear-gradient(180deg,rgba(12,22,34,.96),rgba(5,10,18,.96));box-shadow:0 18px 50px rgba(0,0,0,.32)}.hero{padding:18px;margin-bottom:12px}.panel{padding:14px;margin:12px 0}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.card{padding:11px}.kicker{margin:0 0 7px;color:#c79337;font:900 11px/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1,h2,h3{margin:0 0 8px;font-family:Georgia,serif;letter-spacing:-.035em}.hint,.tiny{color:#b9af9d;font-size:12px;line-height:1.45}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.btn{border:1px solid rgba(243,234,215,.18);border-radius:999px;background:#111c2b;color:#f3ead7;padding:8px 12px;font-weight:900;cursor:pointer;text-decoration:none}.btn.primary{background:#14f195;color:#06130d;border-color:#14f195}.btn.warn{background:rgba(255,215,110,.14);color:#fff0b8}.btn:disabled{opacity:.45;cursor:not-allowed}.stat b{display:block;font-size:22px;color:#fff}.ok{color:#14f195}.bad{color:#ff705c}label{display:grid;gap:5px;font-weight:900;color:#d8cfb7}input,textarea,select{border:1px solid rgba(243,234,215,.18);border-radius:12px;background:#07101a;color:#f3ead7;padding:9px;font:inherit;min-width:0}input[type=checkbox]{width:22px;height:22px}.mono{font:12px/1.35 ui-monospace,monospace;white-space:pre-wrap;max-height:320px;overflow:auto;background:rgba(0,0,0,.2);border-radius:12px;padding:10px}.table{display:grid;gap:7px}.table-row{display:grid;grid-template-columns:120px minmax(0,1fr) 130px 130px;gap:8px;align-items:center;padding:8px;border-radius:12px;background:rgba(255,255,255,.045);border:1px solid rgba(255,255,255,.07)}.pill{display:inline-flex;width:max-content;border-radius:999px;border:1px solid rgba(255,255,255,.12);background:rgba(255,255,255,.06);padding:3px 8px;font:900 11px/1 ui-monospace,monospace}.danger{color:#ffb8ac}.env{border-color:rgba(20,241,149,.22);background:rgba(20,241,149,.06)}@media(max-width:900px){.grid,.form{grid-template-columns:1fr 1fr}.table-row{grid-template-columns:1fr}.admin-bank{padding:10px}}@media(max-width:560px){.grid,.form{grid-template-columns:1fr}}`;

function byId(id:string){return document.getElementById(id) as HTMLInputElement|null}
const val=(id:string)=>byId(id)?.value||"";
const checked=(id:string)=>!!byId(id)?.checked;
function short(s:string){s=String(s||"");return s.length>18?s.slice(0,8)+"…"+s.slice(-8):s||"—"}
function statusLabel(v:any){const s=String(v||"pending").toLowerCase(); if(s==="dry-run"||s==="check") return "checked"; if(s==="sent") return "sent"; if(s==="pending") return "pending"; return s;}
function headers(){return {"Content-Type":"application/json", ...adminKeyHeaders(adminKey)};}
async function api(action:string, body:any={}){busy=true;err="";msg="";paint();try{return await m.measure.root({start:()=>`POST ${action}`,end:(r:any)=>({ok:r?.ok, msg:r?.msg})},async()=>{const r=await fetch('/api/admin/bank',{method:'POST',headers:headers(),body:JSON.stringify({action,adminKey,...body})});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(explainAdminError(j)||j?.msg||r.statusText);return j;});}catch(e:any){err=String(e?.message||e);return null}finally{busy=false;paint();}}
async function load(){busy=true;err="";paint();try{data=await m.measure.root({start:()=>"GET bank studio",end:(r:any)=>({enabled:r?.bank?.config?.enabled,deposits:r?.bank?.deposits?.length,withdrawals:r?.bank?.withdrawals?.length})},async()=>{const qs=adminKey?`?key=${encodeURIComponent(adminKey)}`:"";const r=await fetch(`/api/admin/bank${qs}`,{cache:'no-store',headers:adminKeyHeaders(adminKey)});const j=await r.json().catch(()=>({}));if(!r.ok||j?.ok===false)throw new Error(explainAdminError(j)||j?.msg||r.statusText);return j;});}catch(e:any){err=String(e?.message||e)}busy=false;paint()}
async function save(){const bank={enabled:checked('bk-enabled'),dryRunOnly:checked('bk-paused'),token:val('bk-token'),tokenAddress:val('bk-token'),tokenLabel:val('bk-label'),bankWallet:val('bk-bank'),treasuryWallet:val('bk-treasury'),rpcEndpoint:val('bk-rpc'),minWithdrawUi:val('bk-min'),decimals:Number(val('bk-decimals')||0)};const r=await api('save-bank',{bank});if(r){msg='Bank config saved.';await load();}}
async function scanAll(){const r=await api('scan-all',{limit:Number(val('scan-limit')||50)});if(r){msg=`Scanned ${r.scannedPlayers||0} deposit wallet(s).`;data={...(data||{}),bank:r.bank||data?.bank};paint();}}
async function checkWithdraw(){const r=await api('check-withdraw',{to:val('check-to'),amountUi:val('check-amount')});if(r){msg=r.msg||'Withdrawal check complete.';data={...(data||{}),bank:r.bank||data?.bank};paint();}}
async function sweepDeposit(dep:string){const r=await api('sweep-deposit',{deposit:dep||val('sweep-deposit')});if(r){msg=r.msg||'Sweep check complete.';data={...(data||{}),bank:r.bank||data?.bank};paint();}}
async function checkBalances(){const r=await api('check-balances');if(r){msg='Balances checked.';data={...(data||{}),bank:r.bank||data?.bank,balances:r.balances};paint();}}
async function processWithdrawals(){const r=await api('process-withdrawals',{limit:Number(val('process-limit')||25)});if(r){msg=r.msg||'Pending withdrawals processed.';data={...(data||{}),bank:r.bank||data?.bank,processResult:r};paint();}}
function Stat({k,v}:{k:string,v:any}){return <div className="card stat"><span className="tiny">{k}</span><b>{String(v??0)}</b></div>}
function Config(){const b=data?.bank||{};const c=b.config||{};return <section className="panel"><h2>Bank config</h2><p className="hint">Configure the token exchange. Token alias or mint should come from <code>SOLCRAFTS_TOKEN</code> (for example <code>solcrafts</code>) or <code>SOLCRAFTS_TOKEN_ADDRESS</code>. The field below can override it locally.</p><div className="form"><label><span>Enabled</span><input id="bk-enabled" type="checkbox" checked={!!c.enabled}/></label><label><span>Pause live transfers</span><input id="bk-paused" type="checkbox" checked={c.dryRunOnly!==false}/></label><label className="env"><span>Token alias / mint</span><input id="bk-token" value={c.token||c.tokenAddress||''} placeholder="SOLCRAFTS_TOKEN=solcrafts"/></label><label><span>Token label</span><input id="bk-label" value={c.tokenLabel||'$CRAFTS'}/></label><label><span>Decimals</span><input id="bk-decimals" type="number" min="0" max="12" value={c.decimals??6}/></label><label><span>Minimum withdrawal</span><input id="bk-min" value={c.minWithdrawUi||'1'}/></label><label><span>Bank wallet</span><input id="bk-bank" value={c.bankWallet||'@dev'}/></label><label><span>Treasury wallet</span><input id="bk-treasury" value={c.treasuryWallet||'@dev'}/></label><label style="grid-column:1/-1"><span>RPC endpoint</span><input id="bk-rpc" value={c.rpcEndpoint||''} placeholder="RPC_ENDPOINT or SOLANA_RPC_ENDPOINT"/></label></div><div className="row" style="margin-top:10px"><button className="btn primary" data-action="save" disabled={busy}>{busy?'Working…':'Save bank config'}</button><span className={c.dryRunOnly!==false?'ok':'danger'}>{c.dryRunOnly!==false?'Live transfers paused':'LIVE TRANSFERS ENABLED'}</span><span className={c.tokenAddress||c.token?'ok':'bad'}>{c.token||c.tokenAddress?'Token configured':'Token missing'}</span></div></section>}
function Operations(){const b=data?.bank||{};const deposits=b.deposits||[];return <section className="panel"><h2>Operations</h2><div className="form"><label><span>Scan limit</span><input id="scan-limit" type="number" value="50"/></label><label><span>Sweep deposit id/address</span><input id="sweep-deposit" placeholder="deposit id or address"/></label><label><span>Withdrawal check wallet</span><input id="check-to" placeholder="Solana wallet address"/></label><label><span>Withdrawal check amount</span><input id="check-amount" value="1"/></label><label><span>Process pending limit</span><input id="process-limit" type="number" value="25"/></label></div><div className="row" style="margin-top:10px"><button className="btn primary" data-action="scan-all" disabled={busy}>Scan all deposits</button><button className="btn" data-action="sweep" disabled={busy}>Check sweep</button><button className="btn" data-action="check-withdraw" disabled={busy}>Check withdrawal</button><button className="btn" data-action="check-balances" disabled={busy}>Check balances</button><button className="btn warn" data-action="process-withdrawals" disabled={busy}>Process pending withdrawals</button></div><p className="hint">This page uses the Sowl bank SDK. Live sends only run when Bank is enabled, transfers are not paused, and token/RPC/wallet env values are configured.</p>{data?.balances?<pre className="mono">{JSON.stringify(data.balances,null,2)}</pre>:null}{data?.processResult?<pre className="mono">{JSON.stringify(data.processResult.results||[],null,2)}</pre>:null}<h3>Deposit wallets</h3><div className="table">{deposits.slice(0,20).map((d:any)=><div className="table-row"><b>Player {d.playerId}</b><code>{short(d.address)}</code><span className="pill">{d.depositId?short(d.depositId):'address'}</span><button className="btn" data-action="sweep-one" data-deposit={d.depositId||d.address}>Check sweep</button></div>)}</div></section>}
function Lists(){const b=data?.bank||{};const withdrawals=(b.withdrawals||[]).slice(0,40).map((w:any)=>({...w,status:statusLabel(w.status),dryRun:undefined,adminDryRun:undefined}));return <section className="panel"><h2>Withdrawals / scans / errors</h2><div className="grid"><Stat k="deposit wallets" v={b.summary?.depositWallets}/><Stat k="withdrawal requests" v={b.summary?.withdrawalRequests}/><Stat k="pending" v={b.summary?.pendingWithdrawals}/><Stat k="last scan rows" v={(b.lastScans||[]).length}/></div><h3>Pending/recent withdrawals</h3><pre className="mono">{JSON.stringify(withdrawals,null,2)}</pre><h3>Deposit scan status</h3><pre className="mono">{JSON.stringify((b.lastScans||[]).slice(0,40),null,2)}</pre><h3>Last errors</h3><pre className="mono">{JSON.stringify((b.lastErrors||[]).slice(0,20),null,2)}</pre></section>}
function App(){const b=data?.bank||{};return <main className="admin-bank"><style>{CSS}</style><section className="hero"><div className="row"><a className="btn" href="/admin">← Admin</a><button className="btn" data-action="reload">Reload</button><a className="btn" href="/admin/debug/economy">Economy debug</a></div><p className="kicker">SolCraft operator</p><h1>Bank Studio</h1><p className="hint">Configure the $CRAFTS exchange, deposit wallets, token mint/address, scans, and withdrawals.</p><div className="form"><label><span>Admin key</span><input id="bk-admin-key" value={adminKey} placeholder="SOLCRAFT_ADMIN_KEY if configured" onInput={(e:any)=>{adminKey=e.currentTarget.value;writeAdminKey(adminKey)}}/></label></div>{err?<p className="bad">{err}</p>:null}{msg?<p className="ok">{msg}</p>:null}{busy?<p className="hint">Working…</p>:null}</section><section className="grid"><Stat k="enabled" v={b.config?.enabled?'yes':'no'}/><Stat k="token" v={b.config?.tokenLabel||'$CRAFTS'}/><Stat k="transfers" v={b.config?.dryRunOnly!==false?'paused':'live'}/><Stat k="deposits" v={b.summary?.depositWallets||0}/></section><Config/><Operations/><Lists/></main>}
function paint(){const root=document.getElementById(rootId);if(root)render(<App/>,root)}
export default function mount(){const root=document.getElementById(rootId);if(!root||mounted)return;mounted=true;adminKey=readAdminKey();root.addEventListener('click',(ev)=>{const el=(ev.target as HTMLElement).closest('[data-action]') as HTMLElement|null;if(!el)return;const a=el.dataset.action;if(a==='reload')load();else if(a==='save')save();else if(a==='scan-all')scanAll();else if(a==='check-withdraw')checkWithdraw();else if(a==='sweep')sweepDeposit('');else if(a==='sweep-one')sweepDeposit(el.dataset.deposit||'');else if(a==='check-balances')checkBalances();else if(a==='process-withdrawals')processWithdrawals();});load()}
