// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
import { explainAdminError, readAdminKey, writeAdminKey } from "../../../client/admin/adminKey";

const rootId = "solcraft-world-sync";
const AUTH_KEY = "solcraft:auth";
let mounted = false;
let adminKey = "";
let prodUrl = "";
let scope = "world";
let busy = false;
let msg = "";
let err = "";
let data:any = { players: [], counts: {} };
let exportPreview:any = null;

const CSS = String.raw`
.ws{min-height:100dvh;padding:16px;background:radial-gradient(circle at 14% 0%,rgba(20,241,149,.13),transparent 34rem),linear-gradient(180deg,#07101a,#03060b);color:#f3ead7;font-family:Outfit,Inter,system-ui,sans-serif}.ws *{box-sizing:border-box}.hero,.panel,.card{border:1px solid rgba(243,234,215,.15);border-radius:22px;background:linear-gradient(180deg,rgba(12,22,34,.96),rgba(5,10,18,.96));box-shadow:0 22px 60px rgba(0,0,0,.34)}.hero{padding:18px;margin-bottom:12px}.layout{display:grid;grid-template-columns:minmax(320px,430px) minmax(0,1fr);gap:12px}.panel{padding:14px;margin-bottom:12px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.k{margin:0 0 7px;color:#ffd76e;font:900 10px/1 ui-monospace,monospace;letter-spacing:.16em;text-transform:uppercase}h1,h2,h3{margin:0;color:#f3ead7;letter-spacing:-.04em}h1{font-family:Georgia,serif;font-size:clamp(36px,6vw,70px);line-height:.9}p{color:#d8cfb7;line-height:1.45}.btn{border:1px solid rgba(243,234,215,.17);border-radius:999px;background:#111c2b;color:#f3ead7;padding:8px 12px;font-weight:900;cursor:pointer;text-decoration:none}.btn.primary{background:#14f195;color:#06120d;border-color:#14f195}.btn.warn{background:rgba(255,215,110,.14);border-color:rgba(255,215,110,.34);color:#ffe6aa}.btn.danger{background:rgba(255,112,92,.15);border-color:rgba(255,112,92,.34);color:#ffd4cc}.btn:disabled{opacity:.5;cursor:not-allowed}.field{display:grid;gap:5px;margin:9px 0}.field label{font:900 10px/1 ui-monospace,monospace;color:#9bffd9;text-transform:uppercase;letter-spacing:.12em}.field input,.field select{width:100%;border:1px solid rgba(243,234,215,.17);border-radius:12px;background:#07101a;color:#f3ead7;padding:9px 10px;font:inherit;outline:none}.good{color:#baffdf}.bad{color:#ffb7aa}.tiny{font:800 11px/1.35 ui-monospace,monospace;color:#b9af9d}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:8px}.stat{padding:10px;border-radius:15px;border:1px solid rgba(255,255,255,.1);background:rgba(255,255,255,.045)}.stat span{display:block;color:#b9af9d;font:900 10px/1 ui-monospace,monospace;text-transform:uppercase}.stat b{display:block;margin-top:5px;color:#fff;font-size:22px}.players{display:grid;gap:8px;max-height:68dvh;overflow:auto}.player{display:grid;gap:5px;padding:10px;border:1px solid rgba(255,255,255,.1);border-radius:16px;background:rgba(255,255,255,.045);color:inherit;text-align:left}.mono{white-space:pre-wrap;font:11px/1.35 ui-monospace,monospace;color:#fff0c8;background:rgba(0,0,0,.22);border-radius:14px;padding:10px;max-height:280px;overflow:auto}@media(max-width:920px){.layout{grid-template-columns:1fr}.players{max-height:none}.ws{padding:10px}}
`;
function qs(){ const q = new URLSearchParams({ scope }); if(adminKey) q.set("adminKey", adminKey); return q; }
async function jsonFetch(url:string, opts:any={}){ const r=await fetch(url,{...opts,headers:{"content-type":"application/json","x-solcraft-admin-key":adminKey,...(opts.headers||{})}}); const j=await r.json().catch(()=>({ok:false,msg:`HTTP ${r.status}`})); if(!r.ok||j.ok===false) throw Object.assign(new Error(j.msg||`HTTP ${r.status}`),{data:j,status:r.status}); return j; }
async function run(fn:any){ busy=true;err="";msg="";paint(); try{await fn()}catch(e:any){err=explainAdminError(e)}finally{busy=false;paint()} }
async function load(){ await run(async()=>{ data=await jsonFetch(`/api/admin/world-sync?${qs().toString()}`); msg="Local world loaded."; }); }
async function requestProductionExport(){
  const origin=prodUrl.replace(/\/+$/,"");
  if(!origin) throw new Error("Enter production origin first.");
  const j=await jsonFetch(`/api/admin/world-sync`,{method:"POST",body:JSON.stringify({action:"exportRemote",origin,scope})});
  return j.snapshot || j;
}
async function previewProd(){ await run(async()=>{ const j=await requestProductionExport(); exportPreview=j; msg=`Production export ready: ${(j.counts?.players||0)} players, ${(j.counts?.tiles||0)} tiles, ${(j.counts?.buildings||0)} buildings.`; }); }
async function importProd(){ await run(async()=>{ let snap=exportPreview; if(!snap){ snap=await requestProductionExport(); exportPreview=snap; } if(!snap) throw new Error("No export to import."); const j=await jsonFetch(`/api/admin/world-sync`,{method:"POST",body:JSON.stringify({action:"import",scope,replace:true,snapshot:snap})}); data=j; msg=`Imported production ${scope} snapshot into local DB.`; }); }
async function loginAs(id:number){ await run(async()=>{ const j=await jsonFetch(`/api/admin/world-sync`,{method:"POST",body:JSON.stringify({action:"impersonate",playerId:id})}); const a=j.auth; localStorage.setItem(AUTH_KEY, JSON.stringify({ pid:a.pid, secret:a.secret, wallet:a.wallet||"", body:a.body||0, hat:a.hat||0, spectator:false })); msg=`Local session switched to ${a.name}. Opening game…`; paint(); setTimeout(()=>{ location.href="/"; },450); }); }
function fmt(n:any){ return Math.floor(Number(n||0)).toLocaleString(); }
function Stats(){ const c=data.counts||{}; return <section className="panel"><h2>Local DB snapshot</h2><div className="grid">{["players","tiles","buildings","doodads","loot","chat","offers","events","meta","redemptions"].filter(k=>k in c).map(k=><div className="stat"><span>{k}</span><b>{fmt(c[k])}</b></div>)}</div></section> }
function SyncPanel(){ return <section className="panel"><h2>Production → local sync</h2><p className="tiny">Production export is fetched through your local server, not directly by the browser, so CORS cannot block it. Production still must have the export route deployed first. Import is local-only by default.</p><div className="field"><label>Admin key</label><input value={adminKey} onInput={(e:any)=>{adminKey=e.currentTarget.value;writeAdminKey(adminKey)}} placeholder="SOLCRAFT_ADMIN_KEY / ADMIN_KEY" /></div><div className="field"><label>Production origin</label><input value={prodUrl} onInput={(e:any)=>{prodUrl=e.currentTarget.value;try{localStorage.setItem("solcraft:prod-origin",prodUrl)}catch{}}} placeholder="https://your-production-domain.com" /></div><div className="field"><label>Scope</label><select value={scope} onInput={(e:any)=>{scope=e.currentTarget.value;load()}}><option value="world">World only: players, map, buildings, chat, meta</option><option value="all">All: includes wallet challenges + token queues</option></select></div><div className="row"><button className="btn" disabled={busy} onClick={load}>Reload local</button><button className="btn warn" disabled={busy} onClick={previewProd}>Preview production export</button><button className="btn primary" disabled={busy||!exportPreview} onClick={importProd}>Import into local DB</button></div>{exportPreview?<pre className="mono">{JSON.stringify({scope:exportPreview.scope,generatedAt:exportPreview.generatedAt,counts:exportPreview.counts,players:(exportPreview.players||[]).slice(0,6)},null,2)}</pre>:null}</section> }
function Players(){ return <section className="panel"><div className="row"><h2>Admin login as local player</h2><button className="btn" disabled={busy} onClick={load}>Reload</button></div><p className="tiny">This writes that player’s local pid/secret into this browser only. Use after importing production into your local DB to inspect their world exactly as they see it.</p><div className="players">{(data.players||[]).map((p:any)=><div className="player"><b>#{p.id} {p.name || "Unnamed"}</b><span className="tiny">{p.wallet?`${String(p.wallet).slice(0,6)}…${String(p.wallet).slice(-4)}`:"no wallet"} · {p.x},{p.z} · tiles {fmt(p.tiles)} · builds {fmt(p.buildings)} · 🪙 {fmt(p.coins)} · 🔬 {fmt(p.science)}</span><div className="row"><button className="btn primary" disabled={busy||!p.hasSecret} onClick={()=>loginAs(p.id)}>Open game as this player</button><a className="btn" href={`/?x=${p.x}&z=${p.z}`}>Open map area</a></div></div>)}</div>{!(data.players||[]).length?<p className="tiny">No players loaded.</p>:null}</section> }
function PlanningNotes(){ return <section className="panel"><h2>Next city-planning decision</h2><p>Once local mirrors production, inspect three real player bases before changing Wonder mechanics. Then decide whether Wonders should be:</p><pre className="mono">{`A) civic anchor: buffs nearby city tiles/buildings\nB) district project: reserves 5×5/7×7/9×9 and unlocks city bonuses\nC) prestige landmark: mostly cosmetic + coins/ranking\n\nRecommended first rule:\nWorld Wonder = district anchor.\nIt reserves a footprint, takes construction time, and gives bonuses to completed buildings inside its district radius.`}</pre></section> }
function App(){return <main className="ws"><style>{CSS}</style><section className="hero"><div className="row"><a className="btn" href="/admin">← Admin</a><a className="btn" href="/admin/player-resources">Player resources</a><a className="btn" href="/">Open game</a></div><p className="k">SolCraft operator</p><h1>World Sync + Player View</h1><p>Mirror the production world into your local SQLite DB, then open the game as any local player to inspect their city, territory, and Wonder placement.</p>{busy?<p className="tiny">Working…</p>:null}{err?<p className="bad">{err}</p>:null}{msg?<p className="good">{msg}</p>:null}</section><section className="layout"><div><SyncPanel/><Stats/></div><div><Players/><PlanningNotes/></div></section></main>}
function paint(){const root=document.getElementById(rootId); if(root) render(<App/>,root)}
export default function mount(){const root=document.getElementById(rootId); if(!root||mounted)return; mounted=true; adminKey=readAdminKey(); try{prodUrl=localStorage.getItem("solcraft:prod-origin")||""}catch{} paint(); load();}
