// @ts-nocheck
/** @jsxImportSource tradjs/client */
import { render } from "tradjs/client";
import { readAdminKey, writeAdminKey, adminKeyHeaders, explainAdminError } from "../../../client/admin/adminKey";

const css = `
.ar{min-height:100vh;background:radial-gradient(circle at 15% 0%,rgba(20,241,149,.12),transparent 32rem),#05080e;color:#f3ead7;padding:18px;font-family:Inter,ui-sans-serif,system-ui}.card{max-width:760px;border:1px solid rgba(243,234,215,.15);border-radius:22px;background:linear-gradient(180deg,rgba(12,22,34,.96),rgba(5,10,18,.96));padding:18px;box-shadow:0 22px 60px rgba(0,0,0,.35)}.kicker{color:#ffd76e;font:900 11px/1 ui-monospace,monospace;letter-spacing:.14em;text-transform:uppercase}h1{font-family:Georgia,serif;font-size:52px;line-height:.9;margin:.1em 0}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.field{display:grid;gap:6px;margin:12px 0}.field label{font:900 11px/1 ui-monospace,monospace;color:#9bffd9;text-transform:uppercase;letter-spacing:.12em}.field input,.field textarea{border:1px solid rgba(243,234,215,.18);border-radius:13px;background:rgba(0,0,0,.24);color:#f3ead7;padding:11px;font:inherit}.btn{border:1px solid rgba(243,234,215,.16);border-radius:999px;background:#111c2b;color:#f3ead7;padding:10px 14px;font-weight:900;cursor:pointer}.btn.primary{background:#14f195;color:#06120d;border-color:#14f195}.tiny{color:#b9af9d;font-size:13px;line-height:1.45}.ok{color:#14f195;font-weight:900}.bad{color:#ff9a88;font-weight:900}.debug{white-space:pre-wrap;font:12px/1.4 ui-monospace,monospace;background:rgba(0,0,0,.24);border:1px solid rgba(243,234,215,.12);border-radius:14px;padding:12px;margin-top:12px}`;
const st={key:readAdminKey(),reason:"World Wonder plazas are now 9×9 and visuals changed. Refresh once so your client renders the update correctly.",status:"",info:null,busy:false};
async function api(path,opts={}){const r=await fetch(path,{...opts,headers:{...(opts.headers||{}),...adminKeyHeaders(st.key)}});const j=await r.json().catch(()=>({}));if(!r.ok||j.ok===false)throw new Error(explainAdminError(j)||j.msg||`HTTP ${r.status}`);return j;}
async function load(){st.busy=true;paint();try{st.info=await api('/api/admin/refresh');st.status='Loaded current refresh version.';}catch(e){st.status=String(e?.message||e);}st.busy=false;paint();}
async function force(){st.busy=true;writeAdminKey(st.key);paint();try{const j=await api('/api/admin/refresh',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({reason:st.reason,key:st.key})});st.info=j;st.status=`Active players will see refresh banner version ${j.version}.`;}catch(e){st.status=String(e?.message||e);}st.busy=false;paint();}
function App(){return <main className="ar"><style>{css}</style><section className="card"><p className="kicker">SolCraft Admin</p><h1>Client Refresh</h1><p className="tiny">Use this after a deploy when the server changed gameplay/client rendering. Online players receive a banner on their next poll and must refresh once.</p><div className="field"><label>Admin key</label><input value={st.key} onInput={e=>{st.key=e.currentTarget.value;writeAdminKey(st.key)}} placeholder="SOLCRAFT_ADMIN_KEY" /></div><div className="field"><label>Reason shown to players</label><textarea rows={3} value={st.reason} onInput={e=>{st.reason=e.currentTarget.value}} /></div><div className="row"><button className="btn" disabled={st.busy} onClick={load}>Check current</button><button className="btn primary" disabled={st.busy} onClick={force}>Force active-player refresh</button><a className="btn" href="/admin">Admin</a></div>{st.status?<p className={st.status.includes('will see')?'ok':'tiny'}>{st.status}</p>:null}<pre className="debug">{JSON.stringify(st.info||{},null,2)}</pre></section></main>}
function paint(){render(<App/>,document.getElementById('admin-refresh-root'));}
paint();load();
